name: controlformulaciones
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  mobile_scanner: ^6.0.6
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.0
  sqflite: ^2.4.1
  pdf: ^3.11.2
  printing: ^5.14.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  open_file: ^3.5.10
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración del ícono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_login.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_login.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_login.png
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf